
server:
  port: 8086

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/doctordb
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

      eureka:
        client:
          serviceUrl:
            defaultZone: http://eureka-server-host:eureka-server-port/eureka/


